# Generated by Django 5.0.8 on 2026-04-26 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FounderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text="Short tagline, e.g. 'Building the future of AI infra'",
                        max_length=160,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Long-form bio, markdown allowed"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("photo_url", models.URLField(blank=True)),
                ("banner_url", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("sectors_of_interest", models.JSONField(blank=True, default=list)),
                (
                    "looking_for",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cofounder", "Co-founder"),
                            ("hires", "Early hires"),
                            ("capital", "Capital"),
                            ("advisors", "Advisors"),
                            ("nothing", "Just connecting"),
                        ],
                        max_length=40,
                    ),
                ),
                ("legal_name", models.CharField(blank=True, max_length=160)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=80)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "is_searchable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this profile shows in the founder directory",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
    ]
