# Generated by Django 5.0.8 on 2026-04-23 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('current_step', models.PositiveSmallIntegerField(default=5)),
                ('bio', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=160)),
                ('stage', models.CharField(choices=[('pre-seed', 'Pre-seed'), ('seed', 'Seed'), ('series-a', 'Series A'), ('series-b', 'Series B+')], default='pre-seed', max_length=20)),
                ('sector', models.CharField(choices=[('ai', 'AI'), ('fintech', 'Fintech'), ('climate', 'Climate'), ('biotech', 'Biotech'), ('deeptech', 'Deep tech'), ('devtools', 'Developer tools')], default='ai', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('revenue', models.CharField(blank=True, max_length=60)),
                ('users', models.CharField(blank=True, max_length=60)),
                ('growth_rate', models.CharField(blank=True, max_length=60)),
                ('previous_funding', models.CharField(blank=True, max_length=240)),
                ('vision', models.TextField(blank=True)),
                ('market', models.TextField(blank=True)),
                ('team', models.TextField(blank=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
    ]
