# Generated by Django 5.0.8 on 2026-04-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="accuracy_attested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="cofounders_count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="application",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="fulltime_count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="application",
            name="incorporated_in",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="application",
            name="incorporation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="one_liner",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="application",
            name="pitch_deck_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="application",
            name="references",
            field=models.TextField(
                blank=True,
                help_text="Names + emails of two investors / operators we can ask about you",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="terms_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="why_now",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="current_step",
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AlterField(
            model_name="application",
            name="sector",
            field=models.CharField(
                choices=[
                    ("ai", "AI"),
                    ("fintech", "Fintech"),
                    ("climate", "Climate"),
                    ("biotech", "Biotech"),
                    ("deeptech", "Deep tech"),
                    ("devtools", "Developer tools"),
                    ("consumer", "Consumer"),
                    ("enterprise", "Enterprise SaaS"),
                ],
                default="ai",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="stage",
            field=models.CharField(
                choices=[
                    ("idea", "Idea"),
                    ("pre-seed", "Pre-seed"),
                    ("seed", "Seed"),
                    ("series-a", "Series A"),
                    ("series-b", "Series B+"),
                ],
                default="pre-seed",
                max_length=20,
            ),
        ),
    ]
